package com.example.ui.theme

import androidx.compose.material3.Typography

// Base typography fallback generated by FontRepository
val Typography: Typography = FontRepository.getTypography(AppFontOption.MODERN_NEO_GROTESQUE)

